// react-version/src/components/FilterBrand.jsx
import React, { useContext } from "react";
import { ProductsContext } from "./../store/Products";
import "./../styles/filter-brand.css";

export default function FilterBrand() {
  const { availableBrands, selectedBrands, setSelectedBrands } = useContext(ProductsContext);
  return (
    <div id="filter-brand" className="filter">
      <h2 className="title">brandz</h2>
      <ul className="list">
        {availableBrands.map((brand, i) => (
          <li key={i}>
            <input
              type="checkbox"
              id={brand}
              value={brand}
              checked={selectedBrands.includes(brand)}
              onChange={(e) => setSelectedBrands(e.target.value)}
            />
            <label className="label" htmlFor={brand}>
              {brand}
            </label>
          </li>
        ))}
      </ul>
    </div>
  );
}

// vue-version/src/components/FilterBrand.vue
<template>
  <div id="filter-brand" class="filter">
    <h2 class="title">brandz</h2>
    <ul class="list">
      <li v-for="(brand, b) in brands" :key="b">
        <input
          type="checkbox"
          :id="brand"
          :value="brand"
          :checked="selected.includes(brand)"
          @input="
            $store.commit('products/setSelectedBrands', $event.target.value)
          "
        />
        <label class="label" :for="brand">{{ brand }}</label>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'FilterBrand',
  computed: {
    brands() {
      return this.$store.getters['products/brands']
    },
    selected() {
      return this.$store.getters['products/selectedBrands']
    }
  }
}
</script>

<style scoped>
#filter-brand .list {
  list-style: none;
  padding: 0;
}
#filter-brand .label {
  cursor: pointer;
}
</style>
