// react-version/src/components/FilterPrice.jsx
import React, { useContext, useState } from "react";
import { ProductsContext } from "./../store/Products";
import "./../styles/filter-price.css";

export default function FilterPrice() {
  const { maxPrice, minPrice, setFilterPrice } = useContext(ProductsContext);
  const [currentSelectedPrice, setCurrentSelectedPrice] = useState(maxPrice);

  const handlePriceChange = (evt) => {
    const newMaxPrice = Number(evt.target.value);
    setFilterPrice(newMaxPrice);
    setCurrentSelectedPrice(newMaxPrice);
  };

  return (
    <div id="filter-price" className="filter">
      <h2 className="title">mula</h2>
      <div className="wrap">
        <input
          type="range"
          onChange={handlePriceChange}
          min={minPrice}
          max={maxPrice}
        />
        <b>{currentSelectedPrice}&euro;</b>
      </div>
    </div>
  );
}

// vue-version/src/components/FilterPrice.vue
<template>
  <div id="filter-price" class="filter">
    <h2 class="title">mula</h2>
    <div class="wrap">
      <input
        type="range"
        @input="$store.commit('products/setMaxPrice', currentSelectedPrice)"
        v-model="currentSelectedPrice"
        :min="minPrice"
        :max="maxPrice"
      />
      <b>{{ currentSelectedPrice }}&euro;</b>
    </div>
  </div>
</template>

<script>
export default {
  name: 'FilterPrice',
  data() {
    return {
      currentSelectedPrice: this.$store.getters['products/maxPrice']
    }
  },
  computed: {
    minPrice() {
      return this.$store.getters['products/minPrice']
    },
    maxPrice() {
      return this.$store.getters['products/maxPrice']
    }
  }
}
</script>

<style scoped>
#filter-price .wrap {
  display: flex;
  align-items: center;
  justify-content: flex-start;
}
</style>
