// vue-version/src/components/FilterReset.vue
<template>
  <div id="filter-reset" class="filter">
    <button class="btn" @click="$store.commit('products/setInitialProducts')">
      reset all
    </button>
  </div>
</template>

<script>
export default {
  name: 'FilterReset'
}
</script>

<style scoped>
.btn {
  height: 32px;
  width: 120px;
  padding: 10px;
  border: 1px dashed;
  background: inherit;
  display: flex;
  justify-content: center;
  align-items: center;
}
</style>

// react-version/src/components/FilterReset.jsx
import React, { useContext } from "react";
import { ProductsContext } from "./../store/Products";
import "./../styles/filter-reset.css";

export default function FilterReset() {
  const { setInitialProducts } = useContext(ProductsContext);

  return (
    <div id="filter-reset" className="filter">
      <button className="btn" onClick={setInitialProducts}>
        reset all
      </button>
    </div>
  );
}
